openapi: 3.0.3
info:
  title: Phase 1 Study & Report Contract
  version: 0.1.0
  description: >
    Canonical schema for UR‑003 (Study Search) and UR‑004 (Report Detail + AI annotations).
paths:
  /api/v1/studies/search:
    get:
      summary: Search studies with pagination and filter options
      parameters:
        - $ref: '#/components/parameters/AuthHeader'
        - $ref: '#/components/parameters/QueryQ'
        - $ref: '#/components/parameters/QueryExamStatus'
        - $ref: '#/components/parameters/QueryExamSource'
        - $ref: '#/components/parameters/QueryExamEquipment'
        - $ref: '#/components/parameters/QueryPatientGender'
        - $ref: '#/components/parameters/QueryExamDescription'
        - $ref: '#/components/parameters/QueryExamRoom'
        - $ref: '#/components/parameters/QueryAgeMin'
        - $ref: '#/components/parameters/QueryAgeMax'
        - $ref: '#/components/parameters/QueryStartDate'
        - $ref: '#/components/parameters/QueryEndDate'
        - $ref: '#/components/parameters/QuerySort'
        - $ref: '#/components/parameters/QueryPage'
        - $ref: '#/components/parameters/QueryPageSize'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudySearchResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
  /api/v1/studies/{exam_id}:
    get:
      summary: Retrieve a single study detail by exam_id
      parameters:
        - $ref: '#/components/parameters/AuthHeader'
        - name: exam_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudyDetail'
        '404':
          $ref: '#/components/responses/NotFound'
  /api/v1/reports/{uid}:
    get:
      summary: Retrieve latest report detail by UID
      parameters:
        - $ref: '#/components/parameters/AuthHeader'
        - name: uid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReportDetail'
        '404':
          $ref: '#/components/responses/NotFound'
  /api/v1/reports/study/{exam_id}:
    get:
      summary: Retrieve latest report detail by study exam_id
      parameters:
        - $ref: '#/components/parameters/AuthHeader'
        - name: exam_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReportDetail'
        '404':
          $ref: '#/components/responses/NotFound'
  /api/v1/ai/annotations/{report_id}:
    get:
      summary: List AI annotations bound to a report
      parameters:
        - $ref: '#/components/parameters/AuthHeader'
        - name: report_id
          in: path
          required: true
          schema:
            type: integer
        - name: annotation_type
          in: query
          required: false
          schema:
            type: string
            enum: [highlight, classification, extraction, scoring, custom]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AIAnnotation'
        '404':
          $ref: '#/components/responses/NotFound'
components:
  parameters:
    AuthHeader:
      name: Authorization
      in: header
      required: true
      schema:
        type: string
      description: Bearer JWT token
    QueryQ:
      name: q
      in: query
      required: false
      schema:
        type: string
        maxLength: 200
    QueryExamStatus:
      name: exam_status
      in: query
      required: false
      schema:
        type: string
    QueryExamSource:
      name: exam_source
      in: query
      required: false
      schema:
        type: string
    QueryExamEquipment:
      name: exam_equipment[]
      in: query
      required: false
      schema:
        type: array
        items:
          type: string
      style: form
      explode: true
    QueryPatientGender:
      name: patient_gender[]
      in: query
      required: false
      schema:
        type: array
        items:
          type: string
          enum: [M, F, U]
      style: form
      explode: true
    QueryExamDescription:
      name: exam_description[]
      in: query
      required: false
      schema:
        type: array
        items:
          type: string
      style: form
      explode: true
    QueryExamRoom:
      name: exam_room[]
      in: query
      required: false
      schema:
        type: array
        items:
          type: string
      style: form
      explode: true
    QueryAgeMin:
      name: patient_age_min
      in: query
      schema:
        type: integer
    QueryAgeMax:
      name: patient_age_max
      in: query
      schema:
        type: integer
    QueryStartDate:
      name: start_date
      in: query
      schema:
        type: string
        format: date
    QueryEndDate:
      name: end_date
      in: query
      schema:
        type: string
        format: date
    QuerySort:
      name: sort
      in: query
      schema:
        type: string
        enum: [order_datetime_desc, order_datetime_asc, patient_name_asc]
    QueryPage:
      name: page
      in: query
      schema:
        type: integer
        minimum: 1
      required: false
    QueryPageSize:
      name: page_size
      in: query
      schema:
        type: integer
        minimum: 1
        maximum: 100
      required: false
  responses:
    BadRequest:
      description: Invalid query parameters
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    Unauthorized:
      description: Missing or invalid token
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
  schemas:
    StudySearchResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/StudyListItem'
        count:
          type: integer
        filters:
          $ref: '#/components/schemas/FilterOptions'
    StudyListItem:
      type: object
      required:
        - exam_id
        - patient_name
        - exam_status
        - exam_source
        - exam_item
        - order_datetime
      properties:
        exam_id:
          type: string
        medical_record_no:
          type: string
          nullable: true
        application_order_no:
          type: string
          nullable: true
        patient_name:
          type: string
        patient_gender:
          type: string
          nullable: true
        patient_age:
          type: integer
          nullable: true
        exam_status:
          type: string
        exam_source:
          type: string
        exam_item:
          type: string
        exam_description:
          type: string
          nullable: true
        order_datetime:
          type: string
          format: date-time
        check_in_datetime:
          type: string
          format: date-time
          nullable: true
        report_certification_datetime:
          type: string
          format: date-time
          nullable: true
        certified_physician:
          type: string
          nullable: true
    FilterOptions:
      type: object
      properties:
        exam_statuses:
          type: array
          items:
            type: string
        exam_sources:
          type: array
          items:
            type: string
        exam_items:
          type: array
          items:
            type: string
        equipment_types:
          type: array
          items:
            type: string
        exam_rooms:
          type: array
          items:
            type: string
        exam_equipments:
          type: array
          items:
            type: string
        exam_descriptions:
          type: array
          items:
            type: string
    StudyDetail:
      allOf:
        - $ref: '#/components/schemas/StudyListItem'
        - type: object
          properties:
            patient_birth_date:
              type: string
              nullable: true
            exam_room:
              type: string
              nullable: true
            exam_equipment:
              type: string
              nullable: true
            equipment_type:
              type: string
            data_load_time:
              type: string
              format: date-time
              nullable: true
    ReportDetail:
      type: object
      required:
        - uid
        - title
        - report_type
        - version_number
        - is_latest
        - content_preview
        - content_raw
        - source_url
      properties:
        uid:
          type: string
        report_id:
          type: string
          nullable: true
        title:
          type: string
        report_type:
          type: string
        version_number:
          type: integer
        is_latest:
          type: boolean
        created_at:
          type: string
          format: date-time
          nullable: true
        verified_at:
          type: string
          format: date-time
          nullable: true
        content_preview:
          type: string
        content_raw:
          type: string
        source_url:
          type: string
    AIAnnotation:
      type: object
      required:
        - id
        - report_id
        - annotation_type
        - user_prompt
        - content
      properties:
        id:
          type: integer
        report_id:
          type: integer
        annotation_type:
          type: string
          enum: [highlight, classification, extraction, scoring, custom]
        user_prompt:
          type: string
        content:
          type: object
          description: Annotation payload (structure depends on type)
        confidence:
          type: number
          format: float
          nullable: true
        raw_response:
          type: string
          nullable: true
        model_name:
          type: string
          nullable: true
        is_edited:
          type: boolean
          default: false
        created_at:
          type: string
          format: date-time
        edited_at:
          type: string
          format: date-time
          nullable: true
    ErrorResponse:
      type: object
      properties:
        detail:
          oneOf:
            - type: string
            - type: array
              items:
                type: object
                properties:
                  loc:
                    type: array
                    items:
                      type: string
                  msg:
                    type: string
                  type:
                    type: string

